#!/usr/bin/env bash

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}

# Only have workspaces for primary monitor
bspc monitor $MONITOR -d {1,2,3,4,5}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r '*'

bspc rule -a Pinentry state=floating center=on
bspc rule -a Emacs split_ratio=0.28 state=tiled
bspc rule -a Firefox split_ratio=0.32
bspc rule -a feh state=fullscreen
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:scratch' state=floating
bspc rule -a '*:scratch' state=floating sticky=on center=on border=off rectangle=1000x800+0+0

# Theme
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 1
bspc config window_gap 0

bspc config normal_border_color "#181a23"
bspc config active_border_color "#181a23"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#bd93f9"

# Extra padding for polybar
bspc config -m primary top_padding 0
bspc config -m primary bottom_padding 34

# background
feh --bg-fill ~/.background-image

# Polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar main >$XDG_DATA_HOME/polybar.log 2>&1 &
echo 'Polybar launched...'
